CFLAGS=-Wall -g

all: 
	/home/jobryan/bin/mpic++ cl21_ana.cpp -o cl21_ana -std=c++11
	/home/jobryan/bin/mpic++ kl31_ana.cpp -o kl31_ana -std=c++11
	/home/jobryan/bin/mpic++ kl22_ana.cpp -o kl22_ana -std=c++11
	/home/jobryan/bin/mpic++ kl22_ana_gnl_1_tnl_1.cpp -o kl22_ana_gnl_1_tnl_1 -std=c++11
	/home/jobryan/bin/mpic++ kl31_ana_gnl_1_tnl_1.cpp -o kl31_ana_gnl_1_tnl_1 -std=c++11
	/home/jobryan/bin/mpic++ kl22_ana_gnl_1_tnl_0.cpp -o kl22_ana_gnl_1_tnl_0 -std=c++11
	/home/jobryan/bin/mpic++ kl31_ana_gnl_1_tnl_0.cpp -o kl31_ana_gnl_1_tnl_0 -std=c++11
	/home/jobryan/bin/mpic++ kl22_ana_gnl_0_tnl_1.cpp -o kl22_ana_gnl_0_tnl_1 -std=c++11
	/home/jobryan/bin/mpic++ kl31_ana_gnl_0_tnl_1.cpp -o kl31_ana_gnl_0_tnl_1 -std=c++11

clean:
	rm -f cl21_ana
	rm -f kl22_ana_gnl_1_tnl_1
	rm -f kl31_ana_gnl_1_tnl_1
	rm -f kl22_ana_gnl_1_tnl_0
	rm -f kl31_ana_gnl_1_tnl_0
	rm -f kl22_ana_gnl_0_tnl_1
	rm -f kl31_ana_gnl_0_tnl_1